Repository broadinstitute/ddp-study-server, pull requests merged in 2020-07, with the labels that each got.

#280 DDP-4772 add GetInvitations API
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/docs/specification/src/endpoints/admin.studies.invitation-lookup.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.invitations.yml
  pepper-apis/docs/specification/src/pepper.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/RouteConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/admin/LookupInvitationResponse.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/invitation/Invitation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/AdminLookupInvitationRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ListUserStudyInvitationsRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/transformers/InstantToIsoInstantUtcStrAdapter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/RouteUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/AdminLookupInvitationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ListUserStudyInvitationsRouteTest.java
Labels: C-feature, I-auth-route

#275 No more liquibase at DDP startup
  .circleci/config.yml
  pepper-apis/config/testing-inmemorydb.conf.ctmpl
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/LiquibaseUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
Labels: C-breaking, R-high

#284 DDP-4792: Fixed issue where new Hebrew language code wasn't recognized.
  pepper-apis/src/main/java/org/broadinstitute/ddp/filter/StudyLanguageResolutionFilter.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/seed/DDP-4792-add-hebrew.xml
  pepper-apis/src/test/java/org/broadinstitute/ddp/filter/StudyLanguageResolutionFilterTest.java
Labels: C-bug

#290 Fix sql issue in Angio patch
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/AngioMigratePrequal.java
Labels: C-bug

#288 Synchronize when mutating LanguageStore
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/cache/LanguageStore.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/content/I18nContentRenderer.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/FormInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiLanguageCode.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/StudyLanguageDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/TemplateDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/filter/StudyLanguageResolutionFilter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/PubSubMessageBuilder.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/AddProfileRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/AdminCreateStudyParticipantRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetStudiesRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PatchProfileRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserRegistrationRoute.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/TxnAwareBaseTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/content/I18nContentRendererTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/SectionBlockDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/QuestionDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/StudyLanguageDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/UserDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/ValidationDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetStudiesRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetStudyDetailRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ListStudyLanguagesRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PatchFormAnswersRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserRegistrationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/ActivityValidationServiceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestDataSetupUtil.java
Labels: C-bug

#289 DDP-4803: Added language codes for Spanish and Chinese and added temp…
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/seed/DDP-4803-hebrew-spanish-chinese.xml
Labels: C-poc

#291 Initialize LanguageStore in more places
  pepper-apis/src/main/java/org/broadinstitute/ddp/cache/LanguageStore.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DataExporterCli.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DataLoaderMain.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/PdfBootstrapperCli.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/StudyDataLoaderMain.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/StudyBuilderCli.java
Labels: C-bug

#292 DDP-4807-add-script-to-retreive-address-pluscode
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/OLCServiceTest.java
Labels: C-enhancement, java

#268 DDP-4615 implement kit scheduling
  pepper-apis/config/application.conf.ctmpl
  pepper-apis/config/testing-inmemorydb.conf.ctmpl
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/client/DsmClient.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/KitConfigurationDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/KitScheduleDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/KitScheduleSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/housekeeping/dao/KitCheckDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/CheckKitsJob.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/Keys.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/types/EventTriggerType.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/dsm/ParticipantKits.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/dsm/ParticipantStatus.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/EventConfiguration.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/kit/KitConfiguration.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/kit/KitSchedule.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/kit/KitScheduleRecord.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/kit/PendingScheduleRecord.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/KitCheckService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DateTimeUtils.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-4615-kit-schedule.xml
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/KitScheduleDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/service/KitCheckService.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/client/DsmClientTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/dsm/ParticipantStatusTrackingInfoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/kit/KitConfigurationTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetDsmParticipantStatusRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/AddressServiceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/KitCheckServiceTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/StudyBuilder.java
  study-builder/studies/study-example.conf
Labels: C-feature, R-3rd-party

#306 circleci: cache testing user token and handle rate limit
  .circleci/config.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/client/ApiResult.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/client/Auth0ManagementClient.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExporter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/PubSubMessageBuilder.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/AdminLookupInvitationRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/SendEmailRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserRegistrationRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/PdfGenerationService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/Auth0Util.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/UserAdminCLI.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/HousekeepingTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/export/DataExporterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/housekeeping/HousekeepingSendgridEmailNotificationTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/DsmRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/AngioAuth0PasswordResetEmailScript.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/MBCAuth0PasswordResetEmailScript.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/StudyPasswordResetEmailGenerator.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/StudyPasswordResetEmailGeneratorTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/WorkflowServiceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/Auth0UtilTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestingUserUtil.java
Labels: C-enhancement

#308 Update more tests to leverage rate limit handling
  pepper-apis/src/main/java/org/broadinstitute/ddp/client/Auth0ManagementClient.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserRegistrationRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/Auth0Util.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DataLoader.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/StudyDataLoader.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/UserAdminCLI.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/Auth0LocalRegistrationTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/DataLoaderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/StudyDataLoaderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestingUserUtil.java
Labels: C-enhancement

#302 Support different event actions when receiving DSM notification
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/EventDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/EventTriggerDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/EventTriggerSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiDsmNotificationTrigger.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiEventTrigger.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiUser.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/UserDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/UserSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/EventConfigurationDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/dsm/DsmNotificationEvent.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/dsm/DsmNotificationPayload.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/DsmNotificationSignal.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/DsmNotificationTrigger.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/DsmExitUserRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/DsmPdfRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/DsmTriggerOnDemandActivityRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetPdfRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/SendDsmNotificationRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/EventService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/RequestUtil.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/RouteUtil.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/EventDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/UserDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/housekeeping/HousekeepingSendgridEmailNotificationTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/EventServiceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/SendDsmNotificationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/WorkflowServiceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestDataSetupUtil.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/EventBuilder.java
Labels: C-breaking, C-enhancement
