Repository broadinstitute/ddp-study-server, pull requests merged in 2020-10, with the labels that each got.

#390 DDP-5032 update TestBoston Spanish translations
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityI18nDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityI18nSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ComponentDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ContentBlockDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/EventDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FormActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockContent.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockGroupHeader.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiFormSection.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiVariableSubstitution.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/SectionBlockDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ValidationDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/BlockContentDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/EventConfigurationDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/FormSectionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/ContentBlockDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/FormActivityDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/FormSectionDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/GroupBlockDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/i18n/SummaryTranslation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/i18n/Translation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/question/TextQuestionDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/validation/RuleDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/AnnouncementEventAction.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/EventConfiguration.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityI18nDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/EventDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiBlockGroupHeader.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/event/NotificationEventActionTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/BuilderUtils.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/EventBuilder.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateActivityBaseSettings.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateActivityNamingDetails.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateTemplatesInPlace.java
  study-builder/studies/testboston/emails/consent_completed.es.html
  study-builder/studies/testboston/emails/result_report_created.es.html
  study-builder/studies/testboston/i18n/es.conf
  study-builder/studies/testboston/study-emails.conf
Labels: C-study, R-high

#398 DDP-5049 count activity summaries after filtering
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/ActivityDefStore.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/activity/ActivityInstanceSummary.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserActivityInstanceListRoute.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityInstanceSql.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/ActivityDefStoreTest.java
Labels: C-enhancement

#404 Ddp 5065 optimize get activity instance status types with Redis caching
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JbdiActivityInstanceStatusTypeCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/activity/ActivityInstanceStatusType.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetActivityInstanceStatusTypeListRoute.java
Labels: C-enhancement

#405 Ddp 5066 optimize get language route
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ListStudyLanguagesRoute.java
Labels: C-enhancement

#409 Fix typo in profile query
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/UserDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/UserDaoTest.java
Labels: C-bug

#412 Prod deployment tweaks20201008
  pepper-apis/config/DataDonationPlatform.yaml.ctmpl
  pepper-apis/config/redisson-jcache.yaml.ctmpl
Labels: D-hotfix

#411 Prion: DDP-5071, update dashboard text
  study-builder/studies/prion/i18n/en.conf
Labels: C-study

#421 Prion: DDP-5108: Update to Prion medical questionnaire
  study-builder/studies/prion/i18n/en.conf
  study-builder/studies/prion/i18n/es.conf
  study-builder/studies/prion/i18n/he.conf
  study-builder/studies/prion/i18n/zh.conf
Labels: C-study

#420 Ddp 5072 study listing header
  study-builder/tenants/prion/loginPage.html
  study-builder/tenants/prion/login_en.json
Labels: C-study

#416 DDP-5102 add Arabic, Portuguese, Vietnamese language codes
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/seed/DDP-5102-add-arabic-portuguese-vietnamese.xml
Labels: C-feature

#436 DDP-5079 testboston: study details in new languages
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiUmbrellaStudyI18n.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/StudyI18nDto.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/StudyBuilder.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateStudyDetails.java
  study-builder/studies/testboston/i18n/ar.conf
  study-builder/studies/testboston/i18n/fr.conf
  study-builder/studies/testboston/i18n/pt.conf
  study-builder/studies/testboston/i18n/ru.conf
  study-builder/studies/testboston/i18n/vi.conf
  study-builder/studies/testboston/i18n/zh.conf
  study-builder/studies/testboston/snippets/consent-section4.conf
Labels: C-study

#438 DDP-5079 testboston: email event templates
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/EventBuilder.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateEmailEventTemplates.java
  study-builder/studies/testboston/study-events.conf
Labels: C-study

#443 DDP-5182: limit fetch size of kit queries
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/TransactionWrapper.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/KitScheduleDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/KitCheckService.java
Labels: C-enhancement, D-hotfix

#440 Updates to testboston Spanish translations
  study-builder/studies/testboston/emails/kit_arrived.es.html
  study-builder/studies/testboston/emails/kit_sent.es.html
  study-builder/studies/testboston/emails/login_account_created.es.html
  study-builder/studies/testboston/emails/next_kit.es.html
  study-builder/studies/testboston/i18n/es.conf
  study-builder/studies/testboston/study-emails.conf
Labels: C-enhancement

#439 testboston: minor text changes
  study-builder/studies/testboston/emails/kit_sent.en.html
  study-builder/studies/testboston/emails/kit_sent.ht.html
  study-builder/studies/testboston/i18n/ar.conf
  study-builder/studies/testboston/i18n/en.conf
  study-builder/studies/testboston/i18n/es.conf
  study-builder/studies/testboston/i18n/fr.conf
  study-builder/studies/testboston/i18n/ht.conf
  study-builder/studies/testboston/i18n/pt.conf
  study-builder/studies/testboston/i18n/ru.conf
  study-builder/studies/testboston/i18n/vi.conf
  study-builder/studies/testboston/i18n/zh.conf
Labels: C-study

#441 Ddp 4346 alphabetize countries
  study-builder/studies/prion/i18n/en.conf
  study-builder/studies/prion/i18n/es.conf
  study-builder/studies/prion/i18n/he.conf
  study-builder/studies/prion/i18n/zh.conf
  study-builder/studies/prion/medical.conf
Labels: C-study

#444 DDP-5133 fix NPE in kit job
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/CheckKitsJob.java
Labels: C-bug

#445 Ddp 5162 internationalize prion password reset
  study-builder/tenants/prion/login.en.json
  study-builder/tenants/prion/passwordReset.en.json
  study-builder/tenants/prion/passwordResetEmail.html
Labels: C-study

#452 DDP-5191 cache pubsub publishers in Housekeeping
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/PubSubConnectionManager.java
Labels: C-enhancement

#446 Remove query for all invitation codes from ES export
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/InvitationDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/InvitationFactory.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ParticipantDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExporter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/StudyExtract.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/study/Participant.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ParticipantDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/export/DataExporterTest.java
Labels: C-bug, D-hotfix, L-housekeeping, java

#455 DDP-5192: limit housekeeping pubsub subscriber threads
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/PubSubConnectionManager.java
Labels: C-enhancement, D-hotfix

#461 DDP-5213 fix participant invite query
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ParticipantDao.sql.stg
Labels: C-bug, D-hotfix

#458 DDP-5196 paginate kit query and narrow transactions
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/KitScheduleDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/CheckKitsJob.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/KitCheckService.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/KitScheduleDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/service/KitCheckService.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/KitCheckServiceTest.java
Labels: C-enhancement

#462 DDP-5215 move to paginated exports
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiUserStudyEnrollment.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/HousekeepingTaskReceiver.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExportCoordinator.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExporter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/OnDemandExportJob.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/StudyDataExportJob.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DataExporterCli.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/export/DataExportCoordinatorTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/export/DataExporterTest.java
Labels: C-enhancement, R-features

#459 Ddp 4654 manual emails
  study-builder/studies/prion/emails/contact_medical_reminder.en.html
  study-builder/studies/prion/emails/contact_medical_reminder.es.html
  study-builder/studies/prion/emails/contact_medical_reminder.he.html
  study-builder/studies/prion/emails/contact_medical_reminder.zh.html
  study-builder/studies/prion/emails/contact_new_study.en.html
  study-builder/studies/prion/emails/contact_new_study.es.html
  study-builder/studies/prion/emails/contact_new_study.he.html
  study-builder/studies/prion/emails/contact_new_study.zh.html
  study-builder/studies/prion/emails/medical_reminder.en.html
  study-builder/studies/prion/emails/medical_reminder.es.html
  study-builder/studies/prion/emails/medical_reminder.he.html
  study-builder/studies/prion/emails/medical_reminder.zh.html
  study-builder/studies/prion/emails/new_study.en.html
  study-builder/studies/prion/emails/new_study.es.html
  study-builder/studies/prion/emails/new_study.he.html
  study-builder/studies/prion/emails/new_study.zh.html
Labels: C-study

#469 DDP-5225 testboston: baseline_symptom no longer write-once
  study-builder/studies/testboston/baseline-symptom.conf
  study-builder/studies/testboston/study-events.conf
Labels: C-study, D-hotfix

#468 Dispose of Liquibase cached data after done updating
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/LiquibaseUtil.java
Labels: C-enhancement

#467 DDP-5224 cache Elasticsearch clients
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExporter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/DataSyncJob.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/OnDemandExportJob.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/schedule/StudyDataExportJob.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/export/DataExporterTest.java
Labels: C-enhancement
