Repository broadinstitute/ddp-study-server, pull requests merged in 2020-12, with the labels that each got.

#534 DDP-5361 sync data after handling DSM notification
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRoute.java
Labels: C-bug, D-hotfix

#536 DDP-5360 don't use keep-alive connections to proxy
  pepper-apis/gae-egress-proxy/squid.conf
  pepper-apis/src/main/java/org/broadinstitute/ddp/client/SendGridClient.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/ElasticsearchServiceUtil.java
Labels: C-bug, D-hotfix

#538 DDP-5367 adjust Hikari db pool timeout configs
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/TransactionWrapper.java
Labels: D-hotfix, R-high

#533 Prion: DDP-4387, set each language's consent link to point to a conse…
  study-builder/studies/prion/i18n/en.conf
  study-builder/studies/prion/i18n/es.conf
  study-builder/studies/prion/i18n/he.conf
  study-builder/studies/prion/i18n/zh.conf
Labels: C-study

#524 DDP-5312 part 1: support kit reasons
  pepper-apis/src/main/antlr4/org/broadinstitute/ddp/pex/lang/Pex.g4
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/EventTriggerDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/EventTriggerSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/EventConfigurationDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/dsm/DsmNotificationPayload.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/dsm/DsmNotificationEventType.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/dsm/KitReasonType.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/ActivityInstanceCreationEventAction.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/DsmNotificationSignal.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/DsmNotificationTrigger.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/pex/TreeWalkInterpreter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRoute.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/pex/TreeWalkInterpreterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRouteTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/EventBuilder.java
Labels: C-breaking

#525 DDP-5312 part 2: export kit-related activity attributes
  elasticsearch/templates/participants_structured.json
  pepper-apis/src/main/java/org/broadinstitute/ddp/content/I18nTemplateConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/content/RenderValueProvider.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExporter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/json/structured/ActivityInstanceRecord.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/dsm/DsmNotificationPayload.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/ActivityInstanceCreationEventAction.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/DsmNotificationSignal.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/study/Participant.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRoute.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/export/DataExporterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/pex/TreeWalkInterpreterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRouteTest.java
Labels: C-breaking, I-elasticsearch

#531 DDP-5312 part 3: pass invite code substitution to study emails
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/PubSubMessageBuilder.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/housekeeping/PubSubMessageBuilderTest.java
Labels: C-feature

#532 DDP-5312 part 4: testboston configurations to enable kit uploads and adhoc symptom survey
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/TestBostonAddSampleCollectMessage.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/TestBostonEnableKitUploads.java
  study-builder/studies/testboston/adhoc-symptom.conf
  study-builder/studies/testboston/emails/adhoc_completed.en.html
  study-builder/studies/testboston/i18n/ar.conf
  study-builder/studies/testboston/i18n/en.conf
  study-builder/studies/testboston/i18n/es.conf
  study-builder/studies/testboston/i18n/fr.conf
  study-builder/studies/testboston/i18n/ht.conf
  study-builder/studies/testboston/i18n/pt.conf
  study-builder/studies/testboston/i18n/ru.conf
  study-builder/studies/testboston/i18n/vi.conf
  study-builder/studies/testboston/i18n/zh.conf
  study-builder/studies/testboston/study-emails.conf
  study-builder/studies/testboston/study-events.conf
Labels: C-study

#543 Ddp 5358 linguistic changes
  study-builder/studies/prion/consent.conf
  study-builder/studies/prion/i18n/en.conf
  study-builder/studies/prion/i18n/es.conf
  study-builder/studies/prion/i18n/he.conf
  study-builder/studies/prion/i18n/zh.conf
  study-builder/tenants/prion/loginPage.html
Labels: C-study

#544 DDP-5312 handle empty set when bulk querying substitutions
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDaoTest.java
Labels: C-bug

#541 DDP-5368 Post-enrollment submission functionality per activity. - Some fixes & improvements
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/src/main/antlr4/org/broadinstitute/ddp/pex/lang/Pex.g4
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestionCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/activity/ActivityInstanceSummary.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/pex/TreeWalkInterpreter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserActivityInstanceListRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/QuestionUtil.java
Labels: C-feature

#547 DDP-5383 log access without token as warning
  pepper-apis/src/main/java/org/broadinstitute/ddp/filter/UserAuthCheckFilter.java
Labels: D-hotfix, I-auth-filter

#542 DDP-5359 return error if lastKitRequestGuid is not found
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/DsmKitRequestDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetDsmKitRequestsRoute.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/DsmKitRequestDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetDsmKitRequestsRouteTest.java
Labels: C-breaking, C-bug

#550 Prion: DDP-5386, language fixes: fixed some language file issues
  study-builder/studies/prion/i18n/zh.conf
  study-builder/tenants/prion/loginPage.html
Labels: C-study

#507 DDP-5277 support revisioning activity naming details
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityI18nDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityI18nSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FormActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiActivityVersion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/i18n/ActivityI18nDetail.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-5277-revision-activity-naming-details.xml
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityI18nDao.sql.stg
  pepper-apis/src/main/resources/sql.conf
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserActivityInstanceListRouteTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/BrainConsentVersion2.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/BrainPediatricsUpdates.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/BrainPrequalV2.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/TestBostonConsentV2.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/TestBostonEnableKitUploads.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateActivityBaseSettings.java
Labels: C-feature

#493 DDP-5259 should not fetch child composite answers
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/AnswerDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionDao.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/QuestionDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceRouteStandaloneTest.java
Labels: C-breaking, C-bug

#551 bugfix for DDP-5395
  pepper-apis/src/main/java/org/broadinstitute/ddp/monitoring/StackdriverMetricsTracker.java
Labels: C-bug

#554 DDP-5400 improve log message for withdrawn participant in ReceiveDsmNotificationRoute
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRoute.java
Labels: C-enhancement

#244 Cleanup hidden answers on submit
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/instance/FormInstance.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PutFormAnswersRoute.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/activity/instance/FormInstanceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PutFormAnswersRouteStandaloneTest.java
Labels: C-breaking, I-elasticsearch

#560 Prion: DDP-5405, configured Auth0CLI
  study-builder/config/manifest-prion.rb
  study-builder/config/manifest-tenant.rb
  study-builder/config/prion-config.json.ctmpl
  study-builder/render.sh
  study-builder/tenants/prion/tenant.yaml
Labels: C-study, I-auth0

#561 Prion: DDP-5411: Removed non-English languages for now since IRB hasn…
  study-builder/studies/prion/study.conf
  study-builder/tenants/prion/loginPage.html
Labels: C-study

#563 DDP-5396 testboston: allow admin login from google-oauth2
  study-builder/config/testboston-config.json.ctmpl
  study-builder/tenants/testboston/rules/link-admin-accounts.js
  study-builder/tenants/testboston/tenant.yaml
Labels: C-study, I-auth0, R-security

#566 DDP-5234 allow study admins to view and edit hidden/read-only activities
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activities.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activity.answers.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activity.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/FormInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/activity/ActivityInstanceSummary.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/instance/ActivityInstance.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/instance/FormInstance.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetActivityInstanceRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PatchActivityInstanceRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PatchFormAnswersRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PutFormAnswersRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserActivityInstanceListRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/RouteUtil.java
  pepper-apis/src/main/resources/sql.conf
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/activity/instance/FormInstanceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PatchFormAnswersRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PutFormAnswersRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserActivityInstanceListRouteTest.java
Labels: C-feature, I-auth-filter, R-security

#573 DDP-5468 testboston: update titles for adhoc symptom activity
  study-builder/studies/testboston/i18n/en.conf
Labels: C-study, D-release
