Repository broadinstitute/ddp-study-server, pull requests merged in 2020-11, with the labels that each got.

#478 Ensure a default language is set in DDPAuth object
  pepper-apis/src/main/java/org/broadinstitute/ddp/security/JWTConverter.java
Labels: C-bug

#475 Downsize Redisson in housekeeping
  .circleci/config.yml
  pepper-apis/api-build.sh
  pepper-apis/config/application.conf.ctmpl
  pepper-apis/config/manifest.rb
  pepper-apis/config/redisson-jcache-housekeeping.yaml.ctmpl
  pepper-apis/configure.rb
Labels: C-breaking, C-enhancement

#480 Prion: DDP-5241, auth0 validation fix: added validation messages to p…
  study-builder/tenants/prion/loginPage.html
Labels: C-study

#482 DDP-5244 fix bug with activity instance numbering
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/ActivityInstanceDao.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/ActivityInstanceDaoTest.java
Labels: C-bug

#474 DDP-5110 slack unfurling and dialing back slack overload
  pepper-apis/parent-pom.xml
  pepper-apis/src/main/java/org/broadinstitute/ddp/log/SlackAppender.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/thread/ThreadFactory.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/thread/ThreadPriorities.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/SlackAppenderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/log/SlackAppenderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GsonUtilTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ProfileRouteTest.java
Labels: C-bug, C-enhancement, L-alerts, R-3rd-party

#487 DDP-5248 fix encoding issue in PostPasswordResetRoute
  pepper-apis/docs/specification/src/endpoints/post-password-reset.yml
  pepper-apis/docs/specification/src/pepper.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PostPasswordResetRoute.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/log/SlackAppenderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PostPasswordResetRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRouteTest.java
Labels: C-breaking, C-bug

#489 Prion: DDP-5256: Internationalized password strength text
  study-builder/tenants/prion/loginPage.html
Labels: C-study

#491 DDP-5254 testboston: add sample collect message to symptom surveys
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/TestBostonAddSampleCollectMessage.java
  study-builder/studies/testboston/baseline-symptom.conf
  study-builder/studies/testboston/i18n/ar.conf
  study-builder/studies/testboston/i18n/en.conf
  study-builder/studies/testboston/i18n/es.conf
  study-builder/studies/testboston/i18n/fr.conf
  study-builder/studies/testboston/i18n/ht.conf
  study-builder/studies/testboston/i18n/pt.conf
  study-builder/studies/testboston/i18n/ru.conf
  study-builder/studies/testboston/i18n/vi.conf
  study-builder/studies/testboston/i18n/zh.conf
  study-builder/studies/testboston/longitudinal-covid.conf
  study-builder/studies/testboston/patches/sample-collect-message.conf
Labels: C-study

#488 DDP-5252 migrate more Auth0 Management API calls to use retries
  pepper-apis/src/main/java/org/broadinstitute/ddp/client/Auth0ManagementClient.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/Auth0Util.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/client/Auth0ManagementClientTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GovernedParticipantRegistrationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserRegistrationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/StudyPasswordResetEmailGenerator.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/StudyPasswordResetEmailGeneratorTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/Auth0LocalRegistrationTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/Auth0UtilTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestingUserUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/UpdateUserLoginDataUtilTest.java
Labels: C-enhancement, R-3rd-party

#492 study-builder: support passing arguments to tasks
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/StudyBuilderCli.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/CustomTask.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateActivityTemplatesInPlace.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateTemplatesInPlace.java
Labels: C-feature, C-study

#502 Prion: DDP-5268: Removed dictionary fields that had the default Auth0…
  study-builder/tenants/prion/loginPage.html
  study-builder/tenants/prion/passwordResetPage.html
Labels: C-study

#406 [bulk-defs part1] refactor: use bulk template query
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/TemplateDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/i18n/Translation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/template/Template.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/template/TemplateVariable.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/TemplateDao.sql.stg
Labels: C-enhancement

#504 Add cleanup to a test
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/DsmTriggerOnDemandActivityRouteTest.java
Labels: C-enhancement

#407 [bulk-defs part2] refactor: consolidate component dtos
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ComponentDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiComponent.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiInstitutionPhysicianComponent.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ComponentDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/InstitutionPhysicianComponentDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/MailingAddressComponentDto.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiComponent.sql.stg
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/BackfillMailingAddressComponentTitle.java
Labels: C-enhancement

#408 [bulk-defs part3] refactor: consolidate question dtos and caching
  pepper-apis/src/main/java/org/broadinstitute/ddp/copy/AnswerToAnswerCopier.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/copy/AnswerToProfileCopier.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockConditionalControl.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiCompositeQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiCompositeQuestionCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestionCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTextQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/PickListQuestionCachedDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/PicklistAnswerDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/PicklistQuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionCachedDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/SectionBlockDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/AgreementQuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/BooleanQuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/CompositeQuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/DateQuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/NumericQuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/PicklistOptionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/PicklistQuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/QuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/TextQuestionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/question/DatePicklistDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PatchFormAnswersRoute.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiBlockConditionalControl.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiBlockQuestion.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiQuestion.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/PicklistQuestionDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/copy/AnswerToAnswerCopierTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/copy/AnswerToProfileCopierTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/JdbiCompositeQuestionTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/JdbiDateQuestionFieldOrderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/JdbiDateQuestionTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/JdbiTextQuestionSuggestionTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/PicklistQuestionDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/QuestionDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/SectionBlockDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PatchFormAnswersRouteStandaloneTest.java
Labels: C-enhancement

#505 Brain pediatrics update.
  study-builder/studies/brain/about-child.conf
  study-builder/studies/brain/child-post-consent.conf
  study-builder/studies/brain/medical-release-minor.conf
  study-builder/studies/brain/patches/pediatrics-study-activities.conf
  study-builder/studies/brain/patches/pediatrics-study-events.conf
  study-builder/studies/brain/snippets/consent-assent-section4-child-instruction.conf
  study-builder/studies/brain/snippets/consent-assent-section4-child-intro.conf
  study-builder/studies/brain/snippets/consent-minors-section1-preamble.conf
  study-builder/studies/brain/snippets/consent-minors-section1-purpose.conf
  study-builder/studies/brain/snippets/consent-minors-section2-intro.conf
  study-builder/studies/brain/snippets/consent-minors-section2-timing.conf
  study-builder/studies/brain/snippets/consent-minors-section3-additional-terms.conf
  study-builder/studies/brain/snippets/thank-you-announcement-msg-child.conf
Labels: C-study, D-release

#499 Ddp 5223 rgp initial setup
  study-builder/studies/rgp/enrollment.conf
  study-builder/studies/rgp/i18n/en.conf
  study-builder/studies/rgp/i18n/es.conf
  study-builder/studies/rgp/prequal.conf
  study-builder/studies/rgp/study.conf
  study-builder/studies/rgp/substitutions.conf
  study-builder/tenants/rgp/pages/login.html
  study-builder/tenants/rgp/pages/password_reset.html
Labels: C-study

#414 [bulk-defs part4] refactor: cleanup question caching
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiAgreementQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBooleanQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBooleanQuestionCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiCompositeQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiCompositeQuestionCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiDateQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiDateQuestionFieldOrder.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiNumericQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiPicklistQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiPicklistQuestionCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiPicklistRenderMode.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiPicklistSelectMode.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTextQuestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTextQuestionCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTextQuestionInputType.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTextQuestionSuggestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/PicklistQuestionCachedDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionCachedDao.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiAgreementQuestion.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiBooleanQuestion.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiCompositeQuestion.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiDateQuestion.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiDateQuestionFieldOrder.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiPicklistQuestion.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiTextQuestion.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/PicklistQuestionDaoTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/AngioRestructureConsent.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/BrainConsentVersion2.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/ddp3934/InsertAngioPlaceholders.java
Labels: C-enhancement

#415 [bulk-defs part5] refactor: bulk queries for activity definition
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/SqlConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ComponentDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ContentBlockDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FormActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockContent.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockGroupHeader.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlockNesting.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiFormSection.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiFormSectionBlock.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestionValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestionValidationCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/SectionBlockDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ValidationDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/BlockGroupHeaderDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/FormActivitySettingDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/FormBlockDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/PicklistOptionDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/ValidationDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/question/AgreementQuestionDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/question/QuestionDef.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiBlockGroupHeader.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiBlockNesting.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiFormSectionBlock.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/QuestionDaoTest.java
Labels: C-enhancement

#498 [bulk-defs part6] refactor: bulk query for validation rules
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/SqlConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiAgeRangeValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiDateRangeValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiIntRangeValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiLengthValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiNumOptionsSelectedValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestionValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiQuestionValidationCached.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiRegexValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ValidationDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/AgeRangeRuleDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/DateRangeRuleDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/IntRangeRuleDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/LengthDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/LengthRuleDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/NumOptionsSelectedDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/NumOptionsSelectedRuleDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/RegexDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/RegexRuleDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/RuleDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/validation/ValidationDto.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiQuestionValidation.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/QuestionDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/ValidationDaoTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/BrainConsentVersion2.java
Labels: C-enhancement

#495 Reduce memory footprint for PDF generation
  .circleci/config.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/PdfDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/handler/EmailNotificationHandler.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/pdf/PdfConfiguration.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/DsmPdfRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetPdfRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/PdfGenerationService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/PdfService.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/PdfDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/JdbiStudyPdfMappingTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/PdfDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/housekeeping/handler/EmailNotificationHandlerTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/PdfGenerationServiceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/PdfTestingUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestDataSetupUtil.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/PdfBuilder.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/AbstractFixReleasePdfDate.java
Labels: C-docs, C-enhancement, C-feature

#503 DDP-5227 testboston: consent v2
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiFormActivityFormSection.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/FormSectionMembershipDto.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/ActivityBuilder.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/TestBostonConsentV2.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateActivityBaseSettings.java
  study-builder/studies/testboston/consent-v2.conf
  study-builder/studies/testboston/i18n/ar.conf
  study-builder/studies/testboston/i18n/en.conf
  study-builder/studies/testboston/i18n/es.conf
  study-builder/studies/testboston/i18n/fr.conf
  study-builder/studies/testboston/i18n/ht.conf
  study-builder/studies/testboston/i18n/pt.conf
  study-builder/studies/testboston/i18n/ru.conf
  study-builder/studies/testboston/i18n/vi.conf
  study-builder/studies/testboston/i18n/zh.conf
  study-builder/studies/testboston/patch-log.conf
  study-builder/studies/testboston/snippets/consent-v2-intro.conf
  study-builder/studies/testboston/snippets/consent-v2-single-page.conf
  study-builder/studies/testboston/subs.conf
Labels: C-study

#471 DDP-5175 support copying answers from previous instance
  pepper-apis/src/main/java/org/broadinstitute/ddp/copy/CopyExecutor.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/CopyConfigurationDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/CopyConfigurationSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/copy/CopyConfiguration.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-5175-copy-from-previous-instance.xml
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/CopyConfigurationDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/copy/CopyExecutorTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/CopyConfigurationDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/event/CopyAnswerEventActionTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/EventBuilder.java
  study-builder/studies/study-example.conf
Labels: C-feature

#481 DDP-5176 support hiding existing instances in Create Instance API
  pepper-apis/docs/specification/src/components/request-bodies.yml
  pepper-apis/docs/specification/src/components/responses.yml
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activities.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/SqlFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityInstanceCreationValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/CreateActivityInstanceRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/ActivityInstanceCreationValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/RouteUtil.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.sql.stg
  pepper-apis/src/main/resources/sql.conf
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/CreateActivityInstanceRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestFormActivity.java
Labels: C-breaking, C-enhancement

#511 circleci: skip job if no meaningful changes
  .circleci/config.yml
Labels: C-enhancement

#513 Ddp 5282 prion translations
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/seed/DDP-5282-db-translations.xml
  study-builder/studies/prion/emails/contact_medical_reminder.es.html
  study-builder/studies/prion/emails/contact_medical_reminder.he.html
  study-builder/studies/prion/emails/contact_medical_reminder.zh.html
  study-builder/studies/prion/emails/contact_new_study.es.html
  study-builder/studies/prion/emails/contact_new_study.he.html
  study-builder/studies/prion/emails/contact_new_study.zh.html
  study-builder/studies/prion/emails/medical_reminder.es.html
  study-builder/studies/prion/emails/medical_reminder.he.html
  study-builder/studies/prion/emails/medical_reminder.zh.html
  study-builder/studies/prion/emails/new_study.es.html
  study-builder/studies/prion/emails/new_study.he.html
  study-builder/studies/prion/emails/new_study.zh.html
  study-builder/studies/prion/i18n/es.conf
  study-builder/studies/prion/i18n/he.conf
  study-builder/studies/prion/i18n/zh.conf
  study-builder/tenants/prion/login.en.json
  study-builder/tenants/prion/loginPage.html
  study-builder/tenants/prion/passwordReset.en.json
  study-builder/tenants/prion/passwordResetEmail.html
Labels: C-study

#509 DDP-5310 Feature/study statistics
  pepper-apis/docs/specification/src/components/responses.yml
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/docs/specification/src/endpoints/studies.statistics.yml
  pepper-apis/docs/specification/src/pepper.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/RouteConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/StatisticsConfigurationDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/filter/AuthPathRegexUtil.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/filter/UserAuthCheckFilter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/statistics/StatisticsFigure.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/statistics/StatisticsFigureItem.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/statistics/StatisticsConfiguration.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/statistics/StatisticsType.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetStudyStatisticsRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/StatisticsUtil.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-5310-create-statistics-types.xml
  pepper-apis/src/main/resources/org/broadinstitute/ddp/util/StatisticsUtil.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetStudyStatisticsRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/StudyBuilder.java
  study-builder/studies/study-example.conf
Labels: C-docs, C-feature, C-study

#516 DDP-5337 testboston: remove longitudinal survey edit timeout
  study-builder/studies/testboston/longitudinal-covid.conf
Labels: C-study

#519 Ddp 5320 prion header fixes
  study-builder/studies/prion/consent.conf
  study-builder/studies/prion/i18n/en.conf
  study-builder/studies/prion/i18n/es.conf
  study-builder/studies/prion/i18n/he.conf
  study-builder/studies/prion/i18n/zh.conf
  study-builder/tenants/prion/loginPage.html
Labels: C-study

#520 Prion: DDP-5348, fixed issue with phone numbers displaying right-to-l…
  study-builder/studies/prion/i18n/he.conf
Labels: C-study

#485 DDP-5246 making new template for updated English kit arrival email
  study-builder/studies/testboston/emails/kit_arrived.en.html
  study-builder/studies/testboston/emails/kit_arrived2.tmpl.html
  study-builder/studies/testboston/study-emails.conf
Labels: C-study

#521 Slack appender config fix
  pepper-apis/config/application.conf.ctmpl
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/log/SlackAppender.java
Labels: C-bug, C-enhancement, D-hotfix
