Repository broadinstitute/ddp-study-server, pull requests merged in 2020-04, with the labels that each got.

#148 Refactor user profile
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/copy/AnswerToProfileCopier.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/UserDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/UserDaoFactory.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiProfile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ParticipantDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/UserDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/UserProfileDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/UserProfileSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/UserProfileDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExporter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/ParticipantExtract.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/PubSubMessageBuilder.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/housekeeping/handler/EmailNotificationHandler.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/Profile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/governance/GovernancePolicy.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/user/User.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/user/UserProfile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/pex/TreeWalkInterpreter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/AddProfileRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetDsmParticipantInstitutionsRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetProfileRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PatchProfileRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserRegistrationRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/security/JWTConverter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/PdfGenerationService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DataLoader.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/StudyDataLoader.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiProfile.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ParticipantDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/UserDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/UserProfileDao.sql.stg
  pepper-apis/src/main/resources/sql.conf
  pepper-apis/src/test/java/org/broadinstitute/ddp/constants/TestConstants.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/copy/AnswerToProfileCopierTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/copy/CopyExecutorTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/QuestionDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/UserDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/UserProfileDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/export/DataExporterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/filter/UserAuthCheckFilterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/housekeeping/handler/EmailNotificationHandlerTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/event/CopyAnswerEventActionTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/pex/TreeWalkInterpreterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/AuthFilterRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/DsmRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ProfileRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/RouteTestUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserRegistrationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/ProfileWithEmail.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/StudyPasswordResetEmailGenerator.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/StudyPasswordResetEmailGeneratorTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/AgeUpServiceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/DataLoaderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/PdfTestingUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/StudyDataLoaderTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestDataSetupUtil.java
Labels: C-enhancement, R-features

#150 Ddp 4134 auth0 client id to be scoped to tenant
  pepper-apis/docs/specification/src/components/request-bodies.yml
  pepper-apis/docs/specification/src/endpoints/temporary-users.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/RouteConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/UserDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ClientDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiClient.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiClientUmbrellaStudy.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ClientDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/CreateTemporaryUserPayload.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/CreateTemporaryUserRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetStudyPasswordPolicyRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PostPasswordResetRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/security/AesUtil.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/security/JWTConverter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/StudyDataLoaderMain.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/UserAdminCLI.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-4134-change-unique-keys-in-client-table.xml
  pepper-apis/src/test/java/org/broadinstitute/ddp/filter/DsmAuthFilterTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/CreateTemporaryUserRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/DsmRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetStudyPasswordPolicyRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PostPasswordResetRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserRegistrationRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/script/RegisterAuth0ClientScript.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestDataSetupUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/TestingUserUtilTest.java
  pepper-apis/src/test/resources/db-testscripts/baseline-seed-test-data.xml
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/StudyBuilder.java
Labels: C-breaking

#155 DDP-4458 reconcile schema for utf8mb4
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-4124-create-per-activity-validation-tables.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-4458-truncate-varchar-for-utf8mb4.xml
  pepper-apis/src/main/resources/db-changes/schema/baseline-umbrella-study.xml
Labels: C-enhancement

#161 Updates the name used for the Auth0 Salt client [DDP-4532]
  study-builder/tenants/register-user-in-pepper.js
Labels: C-breaking, C-study, D-release, I-auth0

#163 [rc_v1.8] data exporter cli: add flag to do all elastic indices
  pepper-apis/src/main/java/org/broadinstitute/ddp/export/DataExporter.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DataExporterCli.java
Labels: D-release

#162 Updates the name used for the Auth0 Salt client [DDP-4532 backport]
  study-builder/tenants/register-user-in-pepper.js
Labels: C-breaking, C-study, I-auth0

#166 Update version in API documentation
  pepper-apis/docs/specification/src/pepper.yml
Labels: D-release

#167 angio: update placeholder for other_cancer_list diagnosis year
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/AngioDiagnosisYearPlaceholder.java
  study-builder/studies/angio/patch-log.conf
Labels: C-study, D-release

#97 Update pull request template to be more checklist-oriented
  .github/pull_request_template.md
  PULL_REQUEST_TEMPLATE.md
Labels: C-enhancement

#156 consolidate databases
  pepper-apis/README.md
  pepper-apis/config/application.conf.ctmpl
  pepper-apis/config/sqlproxy.env.ctmpl
  pepper-apis/config/testing-inmemorydb.conf.ctmpl
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/DatabaseBackup.java
  scripts/consolidate-db/consolidate.sh
  scripts/consolidate-db/example-config.json
  scripts/consolidate-db/utf8mb4.tmpl.sql
Labels: C-breaking, D-downtime, R-high

#178 Update script and configuration to handle changes currently in develop
  study-builder/config/application.conf.ctmpl
  study-builder/render.sh
Labels: C-bug

#176 DDP-4551: Cross-study registration bug: Auth0 rule
  study-builder/tenants/register-user-in-pepper.js
Labels: C-bug, I-auth0, R-features

#182 Add CI checks for study-builder
  .circleci/config.yml
  pepper-apis/parent-pom.xml
Labels: C-enhancement
