Repository broadinstitute/ddp-study-server, pull requests merged in 2021-08, with the labels that each got.

#954 Squid restart policy [DDP-6748]
  pepper-apis/gae-egress-proxy/Dockerfile
  pepper-apis/gae-egress-proxy/docker-compose.yaml
Labels: C-enhancement, D-downtime

#953 PanCan body location list update [DDP-6747]
  study-builder/studies/pancan/i18n/en.conf
  study-builder/studies/pancan/i18n/es.conf
  study-builder/studies/pancan/snippets/question-body-loc.conf
Labels: C-study

#970 Study builder optimizations
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/DBUtils.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiPicklistOption.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTemplate.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTemplateVariable.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiTextQuestionSuggestion.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiVariableSubstitution.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/PicklistQuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/QuestionDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/TemplateDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/template/TemplateVariable.java
Labels: C-docs

#974 Add User Profile PATCH to temp user allow list
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
Labels: C-bug

#972 Diagnostic Cancer list update [DDP-6771]
  study-builder/studies/pancan/i18n/en.conf
  study-builder/studies/pancan/i18n/es.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-additional.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-blood.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-brain.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-breast.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-endocrine.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-gastro.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-genitourinary.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-gynecologic.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-head-neck.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-leukemia.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-lungs.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-lymphomas.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-melanomas.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-mpns.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-sarcomas.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-skin.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-thymic.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups-thyroid.conf
  study-builder/studies/pancan/snippets/common/cancer-picklist-groups.conf
  study-builder/studies/pancan/subs.conf
Labels: R-high, C-study

#982 Add retries to retrieval of default address from snapshot functionality
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/AddressService.java
Labels: C-bug
