Repository broadinstitute/ddp-study-server, pull requests merged in 2021-02, with the labels that each got.

#598 API Changes to support Family History UI
  pepper-apis/docs/specification/package-lock.json
  pepper-apis/docs/specification/src/components/responses.yml
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activities.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activity.summary.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activity.yml
  pepper-apis/docs/specification/src/pepper.yml
Labels: C-feature

#616 [DDP-3709] part 1: file upload support and API
  pepper-apis/config/application.conf.ctmpl
  pepper-apis/config/testing-inmemorydb.conf.ctmpl
  pepper-apis/docs/specification/src/components/parameters.yml
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activity.uploads.yml
  pepper-apis/docs/specification/src/pepper.yml
  pepper-apis/parent-pom.xml
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/RouteConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FileUploadDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FileUploadSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/CreateUserActivityUploadPayload.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/CreateUserActivityUploadResponse.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/files/FileUpload.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/files/FileUploadStatus.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/CreateUserActivityUploadRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/FileUploadService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/GuidUtils.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/QuestionUtil.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-3709-file-upload.xml
  pepper-apis/src/main/resources/db-changes/seed/DDP-3709-file-upload-status.xml
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/FileUploadDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/CreateUserActivityUploadRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/FileUploadServiceTest.java
Labels: C-feature, I-auth-route

#623 [DDP-3709] part 3: file scanner service
  cf-file-scanner/.gcloudignore
  cf-file-scanner/.gitignore
  cf-file-scanner/README.md
  cf-file-scanner/build-clamav-inside-docker.sh
  cf-file-scanner/build-clamav.sh
  cf-file-scanner/config/example.env
  cf-file-scanner/deploy.sh
  cf-file-scanner/freshclam.conf
  cf-file-scanner/init-bucket-event.sh
  cf-file-scanner/pom.xml
  cf-file-scanner/src/main/java/org/broadinstitute/ddp/cf/FileScanner.java
Labels: C-feature, C-infosec, R-3rd-party, R-security

#632 Ddp 5092 rgp enrollment survey
  study-builder/studies/rgp/enrollment.conf
  study-builder/studies/rgp/i18n/en.conf
  study-builder/studies/rgp/i18n/es.conf
  study-builder/studies/rgp/study.conf
Labels: C-study

#621 DDP-5235 - implement 1st version of API for listening DSM tasks
  .circleci/config.yml
  pepper-apis/config/application.conf.ctmpl
  pepper-apis/config/testing-inmemorydb.conf.ctmpl
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/Housekeeping.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/ConfigFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/UserProfileSql.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTask.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskConnectionService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskException.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskLogUtil.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskProcessor.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskProcessorAbstract.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskProcessorFactory.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskProcessorFactoryAbstract.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskReceiver.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskResult.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskResultMessageCreator.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskResultSender.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/api/ResultSender.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/impl/PubSubTaskProcessorFactoryImpl.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/impl/updateprofile/UpdateEmailHandler.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/impl/updateprofile/UpdateFirstLastNameHandler.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/impl/updateprofile/UpdateProfileConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/event/pubsubtask/impl/updateprofile/UpdateProfileProcessor.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/ConfigUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/event/pubsubtask/PubSubTaskTestUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/event/pubsubtask/api/PubSubTaskCustomMessageTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/event/pubsubtask/impl/updateprofile/PubSubTaskUpdateProfileMessageTest.java
Labels: help wanted

#633 atcp: refactor study contact cloud function
  cf-atcp-contact/.gcloudignore
  cf-atcp-contact/.gitignore
  cf-atcp-contact/README.md
  cf-atcp-contact/config/example.env
  cf-atcp-contact/deploy.sh
  cf-atcp-contact/pom.xml
  cf-atcp-contact/src/main/java/org/broadinstitute/ddp/cf/ATCPStudyContact.java
  cf-atcp-contact/src/main/java/org/broadinstitute/ddp/cf/RecaptchaClient.java
  cf-atcp-contact/src/main/java/org/broadinstitute/ddp/cf/json/Attachment.java
  cf-atcp-contact/src/main/java/org/broadinstitute/ddp/cf/json/FileUploadUrl.java
  cf-atcp-contact/src/main/java/org/broadinstitute/ddp/cf/json/StudyContactRequest.java
  cloud-functions/cf-study-contact/config/function.conf.ctmpl
  cloud-functions/cf-study-contact/config/manifest.rb
  cloud-functions/cf-study-contact/render.sh
  cloud-functions/cf-study-contact/src/main/java/org/broadinstitute/ddp/cf/StudyContactFunction.java
Labels: I-nonauth-route, R-high, R-security

#635 atcp: refactor emailer cloud function
  cf-atcp-emailer/.gcloudignore
  cf-atcp-emailer/.gitignore
  cf-atcp-emailer/README.md
  cf-atcp-emailer/config/example.env
  cf-atcp-emailer/deploy.sh
  cf-atcp-emailer/pom.xml
  cf-atcp-emailer/src/main/java/org/broadinstitute/ddp/cf/ATCPContactEmailer.java
  cloud-functions/cf-emailer/config/function.conf.ctmpl
  cloud-functions/cf-emailer/config/manifest.rb
  cloud-functions/cf-emailer/pom.xml
  cloud-functions/cf-emailer/render.sh
  cloud-functions/cf-emailer/src/main/java/org/broadinstitute/ddp/cf/AttachmentLoadedFunction.java
Labels: R-security

#639 DDP-5637 log warning when DSM notification not handled for withdrawn
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/ReceiveDsmNotificationRoute.java
Labels: L-alerts

#645 DDP-5538: Auth0 UI Improvements
  study-builder/tenants/rgp/emails/verify_email.html
  study-builder/tenants/rgp/pages/login.html
  study-builder/tenants/rgp/tenant.yaml
Labels: C-study, R-security, javascript

#636 cf-file-scanner: cloud function for file malware scanning
  cf-file-scanner/.gcloudignore
  cf-file-scanner/.gitignore
  cf-file-scanner/README.md
  cf-file-scanner/build-clamav-inside-docker.sh
  cf-file-scanner/build-clamav.sh
  cf-file-scanner/config/example.env
  cf-file-scanner/deploy.sh
  cf-file-scanner/freshclam.conf
  cf-file-scanner/init-bucket-event.sh
  cf-file-scanner/pom.xml
  cf-file-scanner/src/main/java/org/broadinstitute/ddp/cf/FileScanner.java
Labels: C-feature, C-infosec, R-3rd-party

#644 DDP-5573 1/3: refactor listing activity instance summaries
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/SqlFile.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FormActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/StudyLanguageCachedDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityInstanceSummaryDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/activity/ActivityInstanceSummary.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserActivityInstanceListRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/ActivityInstanceService.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.sql.stg
  pepper-apis/src/main/resources/sql.conf
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/ActivityInstanceDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/FormActivityDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PutFormAnswersRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/ServerInSameProcessIntegrationTestSuite.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserActivityInstanceListRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/ActivityInstanceServiceTest.java
Labels: C-breaking, C-enhancement

#641 DDP-5573 2/3: support child activities and child instances
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceStatusDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FormActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiActivity.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiActivityInstance.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityInstanceDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityInstanceSummaryDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/ActivityDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/ConsentActivityDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/FormActivityDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/ActivityInstanceCreationEventAction.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/CreateActivityInstanceRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/DsmTriggerOnDemandActivityRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/ActivityInstanceService.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-5573-activity-nesting.xml
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.sql.stg
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/JdbiActivityInstance.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/ActivityInstanceDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/ActivityInstanceStatusDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/FormActivityDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/JdbiActivityTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/PicklistQuestionDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/SectionBlockDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/event/ActivityInstanceCreationEventActionTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/DsmTriggerOnDemandActivityRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetDsmTriggeredInstancesRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PatchFormAnswersRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PutFormAnswersRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserActivityInstanceListRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/util/StudyDataLoaderTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/ActivityBuilder.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/EventBuilder.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/AngioMigratePrequal.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateActivityBaseSettings.java
  study-builder/studies/study-example.conf
Labels: C-feature, C-study, R-features

#656 DDP-5573 fix creation event handling of child activities
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/event/ActivityInstanceCreationEventAction.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/event/ActivityInstanceCreationEventActionTest.java
Labels: C-bug

#648 DDP-5573 3/3: handle parent/child instance status updates
  pepper-apis/docs/specification/src/components/responses.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activity.answers.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/UserActivityInstanceSummary.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/instance/FormInstance.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PatchFormAnswersRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/PutFormAnswersRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/ActivityInstanceService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/ActivityInstanceUtil.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/model/activity/instance/FormInstanceTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PatchFormAnswersRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/PutFormAnswersRouteStandaloneTest.java
Labels: C-feature, R-high

#649 DDP-5582 support nested activity blocks
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/ActivityDefStore.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/SectionBlockDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FormActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiActivity.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiBlock.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/SectionBlockDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/NestedActivityBlockDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/FormBlockDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/NestedActivityBlockDef.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/instance/FormInstance.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/instance/NestedActivityBlock.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/types/BlockType.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/types/NestedActivityRenderHint.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetActivityInstanceRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/ActivityInstanceService.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-5582-nested-activity-block.xml
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/FormActivityDaoTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/service/ActivityInstanceServiceTest.java
Labels: C-feature

#650 DDP-5571 activity instance summary API
  pepper-apis/src/main/java/org/broadinstitute/ddp/DataDonationPlatform.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/constants/RouteConstants.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityInstanceSummaryDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetActivityInstanceSummaryRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/UserActivityInstanceListRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/ActivityInstanceService.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/util/RouteUtil.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceSummaryRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/IntegrationTestSuite.java
Labels: C-feature, I-auth-route

#651 DDP-5585 include parent instance guid in API responses
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/activity/ActivityInstanceSummary.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/instance/ActivityInstance.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/GetActivityInstanceRoute.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/service/ActivityInstanceService.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceRouteStandaloneTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/GetActivityInstanceSummaryRouteTest.java
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/UserActivityInstanceListRouteStandaloneTest.java
Labels: C-feature

#652 DDP-5574 update create instance endpoint to require parent instance
  pepper-apis/docs/specification/src/components/schemas.yml
  pepper-apis/docs/specification/src/endpoints/user.studies.activities.yml
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityInstanceCreationValidation.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/json/ActivityInstanceCreationPayload.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/route/CreateActivityInstanceRoute.java
  pepper-apis/src/main/resources/org/broadinstitute/ddp/db/dao/ActivityInstanceDao.sql.stg
  pepper-apis/src/test/java/org/broadinstitute/ddp/route/CreateActivityInstanceRouteTest.java
Labels: C-docs, C-feature

#653 DDP-5604 support canDeleteInstances activity definition flag
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/FormActivityDao.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiActivity.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dto/ActivityDto.java
  pepper-apis/src/main/java/org/broadinstitute/ddp/model/activity/definition/ActivityDef.java
  pepper-apis/src/main/resources/changelog-master.xml
  pepper-apis/src/main/resources/db-changes/schema/DDP-5604-activity-can-delete-instances.xml
  pepper-apis/src/test/java/org/broadinstitute/ddp/db/dao/FormActivityDaoTest.java
  study-builder/src/main/java/org/broadinstitute/ddp/studybuilder/task/UpdateActivityBaseSettings.java
Labels: C-feature

#659 DDP-5659 fix model notification in JdbiUmbrellaStudyCached
  pepper-apis/src/main/java/org/broadinstitute/ddp/db/dao/JdbiUmbrellaStudyCached.java
Labels: C-bug, help wanted
